import pandas as pd

import plotly.express as px

from . import data, years
from .base_page import get_base_layout

indicators_dict = {
    "VIOLENCE": {
        "NAME": "Violence against Children and Women",
        "CARDS": [
            {
                "name": "Population subjected to physical violence in the previous 12 months",
                "indicator": "PT_VC_VOV_PHYL",
                "suffix": "Percentage range among countries",
                "min_max": True,
            },
            {
                "name": "Adults who think that physical punishment is necessary to raise/educate children",
                "indicator": "PT_ADLT_PS_NEC",
                "suffix": "Percentage range among countries",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Violence and Assault",
            "geo": "Country_name",
            "options": dict(
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 62.995158, "lon": 88.048713},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Country_name": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Country_name": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH",
                "PT_F_GE15_SX_V_PTNR_12MNTH",
                "PT_VC_VOV_PHYL",
                "PT_VC_VOV_SEXL",
                "PT_VC_VOV_ROBB",
                "PT_VC_SNS_WALN",
                "PT_CHLD_1-14_PS-PSY-V_CGVR",
                "PT_F_18-29_SX-V_AGE-18",
                "PT_M_18-29_SX-V_AGE-18",
                "PT_VC_PRR_PHYV",
                "PT_VC_PRR_SEXV",
                "PT_VC_PRR_ROBB",
                "PT_ADLT_PS_NEC",
                "PT_F_15-49_W-BTNG",
                "PT_M_15-49_W-BTNG",
                "PT_ST_13-15_BUL_30-DYS",
            ],
            "default": "PT_ADLT_PS_NEC",
        },
        "AREA_1": {
            "name": "Violent Discipline",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "indicators": [
                "PT_CHLD_1-14_PS-PSY-V_CGVR",
                "PT_ADLT_PS_NEC",
                "PT_ST_13-15_BUL_30-DYS",
            ],
            "default": "PT_ADLT_PS_NEC",
        },
        "AREA_2": {
            "name": "Violence, Assault, and Safety",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH",
                "PT_F_GE15_SX_V_PTNR_12MNTH",
                "PT_VC_VOV_PHYL",
                "PT_VC_VOV_SEXL",
                "PT_VC_VOV_ROBB",
                "PT_VC_SNS_WALN",
                "PT_F_18-29_SX-V_AGE-18",
                "PT_M_18-29_SX-V_AGE-18",
                "PT_VC_PRR_PHYV",
                "PT_VC_PRR_SEXV",
                "PT_VC_PRR_ROBB",
                "PT_F_15-49_W-BTNG",
                "PT_M_15-49_W-BTNG",
                "PT_CHLD_VIOLENCE_WELFARE",
                "PT_CHLD_DISAB_VIOLENCE_WELFARE",
                "PT_CHLD_VIOLENCE_HEALTHCARE",
                "PT_CHLD_DISAB_VIOLENCE_HEALTHCARE",
                "PT_CHLD_VIOLENCE_EDUCATION",
                "PT_CHLD_DISAB_VIOLENCE_EDUCATION",
            ],
            "default_graph": "bar",
            "default": "PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH",
        },
    },
    "CARE": {
        "NAME": "Children without parental care",
        "CARDS": [
            {
                "name": "aged 0-17 in formal residential care (at the end of the year)",
                "indicator": "PT_CHLD_INRESIDENTIAL",
                "suffix": "Total number of children",
                "sex": "_T",
                "age": "_T",
                "absolute": True,
            },
            {
                "name": "aged 0-17 in formal foster care (at the end of the year)",
                "indicator": "PT_CHLD_CARED_BY_FOSTER",
                "suffix": "Total number of children",
                "sex": "_T",
                "age": "_T",
                "absolute": True,
            },
        ],
        "MAIN": {
            "name": "Family Environment",
            "geo": "Country_name",
            "options": dict(
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 62.995158, "lon": 88.048713},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Country_name": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Country_name": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PT_CHLD_INFORMALCARE_RATE",
                "PT_CHLD_INRESIDENTIAL",
                "PT_CHLD_INRESIDENTIAL_RATE_B",
                "PT_CHLD_DISAB_INRESIDENTIAL",
                "PT_CHLD_DISAB_INRESIDENTIAL_PROP",
                "PT_YOUNG_INRESIDENTIAL",
                "PT_YOUNG_DISAB_INRESIDENTIAL",
                "PT_CHLD_ENTER_RESIDENTIAL_RATE",
                "PT_CHLD_DISAB_ENTER_RESIDENTIAL_PROP",
                "PT_CHLD_LEFT_RESIDENTIAL",
                "PT_CHLD_DISAB_LEFT_RESIDENTIAL_PROP",
                "PT_YOUNG_LEFT_RESIDENTIAL",
                "PT_YOUNG_DISAB_LEFT_RESIDENTIAL",
                "PT_CHLD_INRESIDENTIAL_PROP",
                "PT_CHLD_INFOSTER_PROP",
                "PT_CHLD_DISAB_INFOSTER_PROP",
                "PT_CHLD_INKINSHIP_PROP",
                "PT_CHLD_DISAB_INKINSHIP_PROP",
                "PT_CHLD_INOTHER_FAMILY_PROP",
                "PT_CHLD_DISAB_INOTHER_FAMILY_PROP",
                "PT_CHLD_DISAB_INFAMILY_PROP",
                "PT_CHLD_ENTEREDFAMILY_RATE",
                "PT_CHLD_DISAB_ENTEREDFAMILY_PROP",
                "PT_YOUNG_INALL_FAMILY",
                "PT_YOUNG_DISAB_INALL_FAMILY",
                "PT_CHLD_CARED_BY_FOSTER",
                "PT_CHLD_DISAB_FOSTER",
                "PT_CHLD_ENTEREDFOSTER",
                "PT_CHLD_DISAB_ENTEREDFOSTER",
                "PT_CHLD_ENTEREDKINSHIP",
                "PT_CHLD_DISAB_ENTEREDKINSHIP",
                "PT_CHLD_ENTEREDOTHER_FAMILY",
                "PT_CHLD_DISAB_ENTEREDOTHER_FAMILY",
                "PT_CHLD_LEFT_ALLFAMILY",
                "PT_YOUNG_LEFT_ALLFAMILY",
                "PT_YOUNG_DISAB_LEFT_ALLFAMILY",
                "PT_CHLD_LEFTFOSTER",
                "PT_CHLD_DISAB_LEFTFOSTER",
                "PT_CHLD_LEFT_KINSHIP",
                "PT_CHLD_DISAB_LEFT_KINSHIP",
                "PT_CHLD_LEFT_FAMILY",
                "PT_CHLD_DISAB_LEFT_FAMILY",
                "PT_CHLD_ALLFAMILY_PROP",
                "PT_CHLD_INCARE_FOSTER_RATE",
                "PT_CHLD_ADOPTION_RATE",
                "PT_CHLD_ADOPTION_INTERCOUNTRY_RATE",
                "PT_CHLD_ADOPT_DOMESTIC_RATE",
                "PT_CHLD_DISAB_ADOPT_PROP",
                "PT_CHLD_DISAB_ADOPT_DOMESTIC_PROP",
                "PT_CHLD_DISAB_ADOPT_INTERCOUNTRY_PROP",
                "PT_CHLD_ADOPTION",
                "PT_CHLD_ADOPTION_DISAB",
            ],
            "default": "PT_CHLD_INFORMALCARE_RATE",
        },
        "AREA_1": {
            "name": "Formal Residencial Care",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "default": "PT_CHLD_INRESIDENTIAL",
            "indicators": [
                "PT_CHLD_INRESIDENTIAL",
                "PT_CHLD_INRESIDENTIAL_RATE_B",
                "PT_CHLD_DISAB_INRESIDENTIAL",
                "PT_CHLD_DISAB_INRESIDENTIAL_PROP",
                "PT_YOUNG_INRESIDENTIAL",
                "PT_YOUNG_DISAB_INRESIDENTIAL",
                "PT_CHLD_ENTER_RESIDENTIAL_RATE",
                "PT_CHLD_DISAB_ENTER_RESIDENTIAL_PROP",
                "PT_CHLD_LEFT_RESIDENTIAL",
                "PT_CHLD_DISAB_LEFT_RESIDENTIAL_PROP",
                "PT_YOUNG_LEFT_RESIDENTIAL",
                "PT_YOUNG_DISAB_LEFT_RESIDENTIAL",
                "PT_CHLD_INRESIDENTIAL_PROP",
            ],
        },
        "AREA_2": {
            "name": "Formal Family-based Care and Adoption",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PT_CHLD_INFOSTER_PROP",
                "PT_CHLD_DISAB_INFOSTER_PROP",
                "PT_CHLD_INKINSHIP_PROP",
                "PT_CHLD_DISAB_INKINSHIP_PROP",
                "PT_CHLD_INOTHER_FAMILY_PROP",
                "PT_CHLD_DISAB_INOTHER_FAMILY_PROP",
                "PT_CHLD_DISAB_INFAMILY_PROP",
                "PT_CHLD_ENTEREDFAMILY_RATE",
                "PT_CHLD_DISAB_ENTEREDFAMILY_PROP",
                "PT_YOUNG_INALL_FAMILY",
                "PT_YOUNG_DISAB_INALL_FAMILY",
                "PT_CHLD_CARED_BY_FOSTER",
                "PT_CHLD_DISAB_FOSTER",
                "PT_CHLD_ENTEREDFOSTER",
                "PT_CHLD_DISAB_ENTEREDFOSTER",
                "PT_CHLD_ENTEREDKINSHIP",
                "PT_CHLD_DISAB_ENTEREDKINSHIP",
                "PT_CHLD_ENTEREDOTHER_FAMILY",
                "PT_CHLD_DISAB_ENTEREDOTHER_FAMILY",
                "PT_CHLD_LEFT_ALLFAMILY",
                "PT_YOUNG_LEFT_ALLFAMILY",
                "PT_YOUNG_DISAB_LEFT_ALLFAMILY",
                "PT_CHLD_LEFTFOSTER",
                "PT_CHLD_DISAB_LEFTFOSTER",
                "PT_CHLD_LEFT_KINSHIP",
                "PT_CHLD_DISAB_LEFT_KINSHIP",
                "PT_CHLD_LEFT_FAMILY",
                "PT_CHLD_DISAB_LEFT_FAMILY",
                "PT_CHLD_ALLFAMILY_PROP",
                "PT_CHLD_INCARE_FOSTER_RATE",
                "PT_CHLD_ADOPTION_RATE",
                "PT_CHLD_ADOPTION_INTERCOUNTRY_RATE",
                "PT_CHLD_ADOPT_DOMESTIC_RATE",
                "PT_CHLD_DISAB_ADOPT_PROP",
                "PT_CHLD_DISAB_ADOPT_DOMESTIC_PROP",
                "PT_CHLD_DISAB_ADOPT_INTERCOUNTRY_PROP",
                "PT_CHLD_ADOPTION",
                "PT_CHLD_ADOPTION_DISAB",
                "PT_CHLD_ADOPT_DOMESTIC",
                "PT_CHLD_DISAB_ADOPT_DOMESTIC",
                "PT_CHLD_ADOPTION_INTERCOUNTRY",
                "PT_CHLD_ADOPTION_INTER_COUNTRY_DISAB",
            ],
            "default_graph": "line",
            "default": "PT_CHLD_CARED_BY_FOSTER",
        },
    },
    "JUSTICE": {
        "NAME": "Justice for Children",
        "CARDS": [
            {
                "name": "detained in pre-sentence detention (during the year)",
                "indicator": "JJ_CHLD_DETENTION",
                "suffix": "Total number of children",
                "sex": "_T",
                "age": "_T",
                "absolute": True,
            },
            {
                "name": "in detention at the end of the year (per 100,000)",
                "indicator": "JJ_CHLD_DETENTION_RATE",
                "suffix": "Rate of children",
                "sex": "_T",
                "age": "_T",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Justice for Children",
            "geo": "Country_name",
            "options": dict(
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 62.995158, "lon": 88.048713},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Country_name": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Country_name": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "JJ_CHLD_VICTIM_CRIME_RATE",
                "JJ_CHLD_WITNESS_CRIME_RATE",
                "JJ_CHLD_DETENTION_RATE",
                "JJ_CHLD_PRE_SENTENCE_DETENTION_RATE",
                "JJ_CHLD_POST_SENTENCE_DETENTION_RATE",
                "JJ_CHLD_ENTER_DETENTION_RATE",
                "JJ_CHLD_ENTER_PRE_SENTENCE_DETENTION_RATE",
                "JJ_CHLD_ENTER_POST_SENTENCE_DETENTION_RATE",
                "JJ_CHLD_CUSTODIAL_SENTENCE_PROP",
                "JJ_CHLD_ALTERNATIVE_SENTENCE_PROP",
                "JJ_CHLD_DETENTION",
                "JJ_VC_PRS_UNSNT",
                "JJ_PRISIONERS",
                "JJ_PRISIONERS_RT",
            ],
            "default": "JJ_CHLD_VICTIM_CRIME_RATE",
        },
        "AREA_1": {
            "name": "Children Victims, Witnesses and Prisoners",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "indicators": [
                "JJ_CHLD_VICTIM_CRIME_RATE",
                "JJ_CHLD_WITNESS_CRIME_RATE",
                "JJ_CHLD_VICTIM_CRIME",
                "JJ_CHLD_WITNESS_CRIME",
                "JJ_PRISIONERS",
                "JJ_PRISIONERS_RT",
            ],
            "default": "JJ_CHLD_VICTIM_CRIME_RATE",
        },
        "AREA_2": {
            "name": "Diversion, Sentencing, and Detention of Children",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "JJ_CHLD_DETENTION_RATE",
                "JJ_CHLD_PRE_SENTENCE_DETENTION_RATE",
                "JJ_CHLD_POST_SENTENCE_DETENTION_RATE",
                "JJ_CHLD_ENTER_DETENTION_RATE",
                "JJ_CHLD_ENTER_PRE_SENTENCE_DETENTION_RATE",
                "JJ_CHLD_ENTER_POST_SENTENCE_DETENTION_RATE",
                "JJ_CHLD_CUSTODIAL_SENTENCE_PROP",
                "JJ_CHLD_ALTERNATIVE_SENTENCE_PROP",
                "JJ_CHLD_DETENTION",
                "JJ_CHLD_PRETRIAL",
                "JJ_CHLD_PRISION_ADJUDICATION",
                "JJ_CHLD_POST_SENTENCE_DETENTION",
                "JJ_CHLD_CUSTODIAL_SENTENCE",
                "JJ_CHLD_ALTERNATIVE_SENTENCE",
                "JJ_VC_PRS_UNSNT",
            ],
            "default_graph": "line",
            "default": "JJ_CHLD_DETENTION_RATE",
        },
    },
    "MARRIAGE": {
        "NAME": "Child marriage and other harmful practices",
        "CARDS": [
            {
                "name": "Women age 20-24 years married or in union before age 18",
                "indicator": "PT_F_20-24_MRD_U18",
                "suffix": "Percentage range among countries",
                "min_max": True,
            },
            {
                "name": "Men age 20-24 years married or in union before age 18",
                "indicator": "PT_M_20-24_MRD_U18",
                "suffix": "Percentage range among countries",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Child Marriage",
            "geo": "Country_name",
            "options": dict(
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 62.995158, "lon": 88.048713},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Country_name": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Country_name": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PT_F_15-19_MRD",
                "PT_M_15-19_MRD",
                "PT_F_20-24_MRD_U15",
                "PT_F_20-24_MRD_U18",
                "PT_M_20-24_MRD_U18",
            ],
            "default": "PT_F_15-19_MRD",
        },
        "AREA_1": {
            "name": "Currently married or in union children age 15-19 years",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "indicators": [
                "PT_F_15-19_MRD",
                "PT_M_15-19_MRD",
            ],
            "default": "PT_F_15-19_MRD",
        },
        "AREA_2": {
            "name": "Currently married or in union adults before age 18 or 15 years",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PT_F_20-24_MRD_U15",
                "PT_F_20-24_MRD_U18",
                "PT_M_20-24_MRD_U18",
            ],
            "default_graph": "bar",
            "default": "PT_F_20-24_MRD_U15",
        },
    },
    "LABOUR": {
        "NAME": "Child labour and other forms of exploitation",
        "CARDS": [
            {
                "name": "Children age 5-17 years who are involved in child labour",
                "indicator": "PT_CHLD_5-17_LBR_ECON-HC",
                "suffix": "Percentage range among countries",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Child labour and other forms of exploitation",
            "geo": "Country_name",
            "options": dict(
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 62.995158, "lon": 88.048713},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Country_name": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Country_name": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PT_CHLD_5-17_LBR_ECON",
                "PT_CHLD_5-17_LBR_ECON-HC",
            ],
            "default": "PT_CHLD_5-17_LBR_ECON",
        },
        "AREA_1": {
            "name": "Child labour - only economic activities",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "indicators": [
                "PT_CHLD_5-17_LBR_ECON",
            ],
            "default": "PT_CHLD_5-17_LBR_ECON",
        },
        "AREA_2": {
            "name": "Child labour - economic activities and household chores",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Country_name",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    # "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Country_name",
                        hover_name="Country_name",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PT_CHLD_5-17_LBR_ECON-HC",
            ],
            "default_graph": "bar",
            "default": "PT_CHLD_5-17_LBR_ECON-HC",
        },
    },
}


main_title = "Family environment and protection from violence and harmful practices"


def get_layout(**kwargs):
    kwargs["indicators"] = indicators_dict
    kwargs["main_title"] = main_title
    return get_base_layout(**kwargs)
