import pandas as pd

import plotly.express as px

from . import data, years
from .base_page import get_base_layout

indicators_dict = {
    "DEMOGRAPHY": {
        "NAME": "Demography about Children",
        "CARDS": [
            {
                "name": "(0-17) living with two parents",
                "indicator": "DM_CHLD_TWO_PRNT",
                "suffix": "Percent of Children",
                "average": True,
                # "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Demographic Info about Child Rights",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "DM_CHLD_TWO_PRNT",
                "DM_FRATE_TOT",
            ],
            "default": "DM_FRATE_TOT",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "DM_CHLD_TWO_PRNT",
                "DM_FRATE_TOT",
            ],
            "default": "DM_FRATE_TOT",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "DM_CHLD_TWO_PRNT",
                "DM_FRATE_TOT",
            ],
            "default_graph": "bar",
            "default": "DM_FRATE_TOT",
        },
    },
    "ECONOMY": {
        "NAME": "Political Economy",
        "CARDS": [
            {
                "name": "by Sex",
                "indicator": "EC_HDI",
                "suffix": "Human Development Index",
            },
            {
                "name": "Unemployment, modelled ILO estimate",
                "indicator": "EC_SL_UEM_TOTL_NE_ZS",
                "suffix": "Percentage of total labor force by sex",
                "average": True,
            },
        ],
        "MAIN": {
            "name": "Child rights political economy",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "EC_HDI",
                "EC_NY_GDP_MKTP_KD_ZG",
                "EC_NY_GDP_PCAP_KD_ZG",
                "EC_NE_DAB_TOTL_ZS",
                "EC_TEC_GRL_GOV_EXP",
                "EC_TEC_CNT_GOV_EXP",
                "EC_TEC_STA_GOV_EXP",
                "EC_TEC_LOC_GOV_EXP",
                "EC_TEC_SSF_EXP",
                "EC_GR_G14_GDP",
                "EDU_FIN_EXP_PT_GDP",
                "HT_SH_XPD_GHED_GD_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_SP_GOV_EXP_TOT",
                "EC_NY_GDP_PCAP_PP_CD",
                "EC_NY_GNP_ATLS_CD",
                "EC_NY_GNP_PCAP_CD",
                "EC_GC_DOD_TOTL_GD_ZS",
                "EC_SI_POV_GINI",
                "EC_SL_UEM_TOTL_NE_ZS",
            ],
            "default": "EC_HDI",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            # compare is the default selection
            "compare": "Sex",
            "default": "EC_NY_GDP_MKTP_KD_ZG",
            "indicators": [
                "EC_HDI",
                "EC_NY_GDP_MKTP_KD_ZG",
                "EC_NY_GDP_PCAP_KD_ZG",
                "EC_NE_DAB_TOTL_ZS",
                "EC_TEC_GRL_GOV_EXP",
                "EC_TEC_CNT_GOV_EXP",
                "EC_TEC_STA_GOV_EXP",
                "EC_TEC_LOC_GOV_EXP",
                "EC_TEC_SSF_EXP",
                "EC_GR_G14_GDP",
                "EDU_FIN_EXP_PT_GDP",
                "HT_SH_XPD_GHED_GD_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_SP_GOV_EXP_TOT",
                "EC_NY_GDP_PCAP_PP_CD",
                "EC_NY_GNP_ATLS_CD",
                "EC_NY_GNP_PCAP_CD",
                "EC_GC_DOD_TOTL_GD_ZS",
                "EC_SI_POV_GINI",
                "EC_SL_UEM_TOTL_NE_ZS",
            ],
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "EC_HDI",
                "EC_NY_GDP_MKTP_KD_ZG",
                "EC_NY_GDP_PCAP_KD_ZG",
                "EC_NE_DAB_TOTL_ZS",
                "EC_TEC_GRL_GOV_EXP",
                "EC_TEC_CNT_GOV_EXP",
                "EC_TEC_STA_GOV_EXP",
                "EC_TEC_LOC_GOV_EXP",
                "EC_TEC_SSF_EXP",
                "EC_GR_G14_GDP",
                "EDU_FIN_EXP_PT_GDP",
                "HT_SH_XPD_GHED_GD_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_SP_GOV_EXP_TOT",
                "EC_NY_GDP_PCAP_PP_CD",
                "EC_NY_GNP_ATLS_CD",
                "EC_NY_GNP_PCAP_CD",
                "EC_GC_DOD_TOTL_GD_ZS",
                "EC_SI_POV_GINI",
                "EC_SL_UEM_TOTL_NE_ZS",
            ],
            "default_graph": "line",
            "default": "EC_NY_GDP_PCAP_KD_ZG",
        },
    },
    "MIGRATION": {
        "NAME": "Migration and Displacement",
        "CARDS": [
            {
                "name": "Net Migration",
                "indicator": "EC_SL_UEM_TOTL_ZS",
                "suffix": "Thousands of Persons",
            },
            {
                "name": "First time asylum applicants",
                "indicator": "DM_ASYL_FRST",
                "suffix": "Persons",
            },
        ],
        "MAIN": {
            "name": "Child Victims of Migration and Displacement",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "EC_SL_UEM_TOTL_ZS",
                "DM_SM_POP_REFG",
                "DM_SM_POP_REFG_OR",
                "DM_ASYL_FRST",
                "DM_ASYL_UASC",
                "MG_INTNL_MG_CNTRY_DEST_PS",
            ],
            "default": "EC_SL_UEM_TOTL_ZS",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "EC_SL_UEM_TOTL_ZS",
                "DM_SM_POP_REFG",
                "DM_SM_POP_REFG_OR",
                "DM_ASYL_FRST",
                "DM_ASYL_UASC",
                "MG_INTNL_MG_CNTRY_DEST_PS",
            ],
            "default": "EC_SL_UEM_TOTL_ZS",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "EC_SL_UEM_TOTL_ZS",
                "DM_SM_POP_REFG",
                "DM_SM_POP_REFG_OR",
                "DM_ASYL_FRST",
                "DM_ASYL_UASC",
                "MG_INTNL_MG_CNTRY_DEST_PS",
            ],
            "default_graph": "line",
            "default": "DM_SM_POP_REFG",
        },
    },
    "RISKS": {
        "NAME": "Risks, humanitarian situation and impact of climate change",
        "CARDS": [
            {
                "name": "of deaths and missing persons attributed to disasters",
                "indicator": "CR_VC_DSR_MTMP",
                "suffix": "Number per 100,000 population",
            },
            {
                "name": "population with primary reliance on clean fuels and technology",
                "indicator": "CR_EG_EGY_CLEAN",
                "suffix": "Proportion of",
                "average": True,
            },
        ],
        "MAIN": {
            "name": "Child Victims of Risks, humanitarian situation and impact of climate change",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "CR_VC_DSR_MTMP",
                "CR_VC_DSR_DAFF",
                "CR_SH_STA_AIRP",
                "CR_SH_STA_ASAIRP",
                "CR_EG_EGY_CLEAN",
                "CR_EG_ACS_ELEC",
                "CR_SG_DSR_LGRGSR",
            ],
            "default": "CR_VC_DSR_MTMP",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "CR_VC_DSR_MTMP",
                "CR_VC_DSR_DAFF",
                "CR_SH_STA_AIRP",
                "CR_SH_STA_ASAIRP",
                "CR_EG_EGY_CLEAN",
                "CR_EG_ACS_ELEC",
                "CR_SG_DSR_LGRGSR",
            ],
            "default": "CR_VC_DSR_MTMP",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "CR_VC_DSR_MTMP",
                "CR_VC_DSR_DAFF",
                "CR_SH_STA_AIRP",
                "CR_SH_STA_ASAIRP",
                "CR_EG_EGY_CLEAN",
                "CR_EG_ACS_ELEC",
                "CR_SG_DSR_LGRGSR",
            ],
            "default": "CR_VC_DSR_MTMP",
            "default_graph": "line",
        },
    },
    "SPENDING": {
        "NAME": "Public spending on children",
        "CARDS": [
            {
                "name": "Government expenditure on education as a percentage of GDP",
                "indicator": "EDU_FIN_EXP_PT_GDP",
                "suffix": "Percent",
                "average": True,
            },
            {
                "name": "Public social expenditure",
                "indicator": "EC_TOT_PUB_EXP_GDP",
                "suffix": "Total Percentage of GDP",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Public spending on children",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "EDU_FIN_EXP_PT_GDP",
                "HT_SH_XPD_GHED_GD_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_TOT_PUB_EXP_GDP",
                "EC_TOT_PUB_EXP_TOT",
                "EC_FAM_PUB_EXP_GDP",
                "EC_FAM_PUB_EXP_TOT",
            ],
            "default": "EC_TOT_PUB_EXP_TOT",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "EDU_FIN_EXP_PT_GDP",
                "HT_SH_XPD_GHED_GD_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_TOT_PUB_EXP_GDP",
                "EC_TOT_PUB_EXP_TOT",
                "EC_FAM_PUB_EXP_GDP",
                "EC_FAM_PUB_EXP_TOT",
            ],
            "default": "EC_TOT_PUB_EXP_TOT",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "EDU_FIN_EXP_PT_GDP",
                "HT_SH_XPD_GHED_GD_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_TOT_PUB_EXP_GDP",
                "EC_TOT_PUB_EXP_TOT",
                "EC_FAM_PUB_EXP_GDP",
                "EC_FAM_PUB_EXP_TOT",
            ],
            "default": "EC_TOT_PUB_EXP_TOT",
            "default_graph": "line",
        },
    },
    "DATA": {
        "NAME": "Data on Children",
        "CARDS": [
            {
                "name": "with national statistical legislation exists that complies with the Fundamental Principles of Official Statistics",
                "indicator": "CR_SG_STT_FPOS",
                "suffix": "Countries",
            },
            {
                "name": "that have conducted at least one population and housing census in the last 10 years",
                "indicator": "CR_SG_REG_CENSUSN",
                "suffix": "Countries",
            },
        ],
        "MAIN": {
            "name": "Child Victims of Crime",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "CR_IQ_SCI_OVRL",
                "CR_SG_STT_FPOS",
                "CR_SG_STT_NSDSFND",
                "CR_SG_STT_NSDSIMPL",
                "CR_SG_STT_NSDSFDGVT",
                "CR_SG_STT_NSDSFDDNR",
                "CR_SG_STT_NSDSFDOTHR",
                "CR_SG_STT_CAPTY",
                "CR_SG_REG_CENSUSN",
            ],
            "default": "CR_IQ_SCI_OVRL",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "CR_IQ_SCI_OVRL",
                "CR_SG_STT_FPOS",
                "CR_SG_STT_NSDSFND",
                "CR_SG_STT_NSDSIMPL",
                "CR_SG_STT_NSDSFDGVT",
                "CR_SG_STT_NSDSFDDNR",
                "CR_SG_STT_NSDSFDOTHR",
                "CR_SG_STT_CAPTY",
                "CR_SG_REG_CENSUSN",
            ],
            "default": "CR_IQ_SCI_OVRL",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "CR_IQ_SCI_OVRL",
                "CR_SG_STT_FPOS",
                "CR_SG_STT_NSDSFND",
                "CR_SG_STT_NSDSIMPL",
                "CR_SG_STT_NSDSFDGVT",
                "CR_SG_STT_NSDSFDDNR",
                "CR_SG_STT_NSDSFDOTHR",
                "CR_SG_STT_CAPTY",
                "CR_SG_REG_CENSUSN",
            ],
            "default": "CR_IQ_SCI_OVRL",
            "default_graph": "line",
        },
    },
}


def get_layout(**kwargs):
    kwargs["indicators"] = indicators_dict
    return get_base_layout(**kwargs)
