import pandas as pd

import plotly.express as px

from . import data, years
from .base_page import get_base_layout

indicators_dict = {
    "HS": {
        "NAME": "Health System",
        "CARDS": [
            {
                "name": "Current health expenditure as a percent of GDP",
                "indicator": "HT_SH_XPD_CHEX_GD_ZS",
                "suffix": "Percent range",
                "min_max": True,
            },
            {
                "name": "Out-of-pocket expenditure - percent of current health expenditure",
                "indicator": "HT_SH_XPD_OOPC_CH_ZS",
                "suffix": "Percent range",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Main Children Health Problems",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "HT_SH_ACS_UNHC",
                "HT_ADOL_UNMETMED_NOUNMET",
                "HT_ADOL_UNMETMED_TOOEXP",
                "HT_ADOL_UNMETMED_TOOFAR",
                "HT_ADOL_UNMETMED_WAITING",
                "HT_ADOL_UNMETMED_TOOEFW",
                "HT_ADOL_UNMETMED_NOTIME",
                "HT_ADOL_UNMETMED_NOKNOW",
                "HT_ADOL_UNMETMED_FEAR",
                "HT_ADOL_UNMETMED_HOPING",
                "HT_ADOL_UNMETMED_OTH",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_CH_ZS",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_PVTD_CH_ZS",
                "HT_SH_XPD_PVTD_PP_CD",
                "HT_SH_XPD_PVTD_PC_CD",
                "HT_SH_XPD_CHEX_PP_CD",
                "HT_SH_XPD_CHEX_PC_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SH_XPD_OOPC_PP_CD",
                "HT_SH_XPD_OOPC_PC_CD",
                "HT_INS_COV",
            ],
            "default": "HT_SH_ACS_UNHC",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "HT_SH_ACS_UNHC",
                "HT_ADOL_UNMETMED_NOUNMET",
                "HT_ADOL_UNMETMED_TOOEXP",
                "HT_ADOL_UNMETMED_TOOFAR",
                "HT_ADOL_UNMETMED_WAITING",
                "HT_ADOL_UNMETMED_TOOEFW",
                "HT_ADOL_UNMETMED_NOTIME",
                "HT_ADOL_UNMETMED_NOKNOW",
                "HT_ADOL_UNMETMED_FEAR",
                "HT_ADOL_UNMETMED_HOPING",
                "HT_ADOL_UNMETMED_OTH",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_CH_ZS",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_PVTD_CH_ZS",
                "HT_SH_XPD_PVTD_PP_CD",
                "HT_SH_XPD_PVTD_PC_CD",
                "HT_SH_XPD_CHEX_PP_CD",
                "HT_SH_XPD_CHEX_PC_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SH_XPD_OOPC_PP_CD",
                "HT_SH_XPD_OOPC_PC_CD",
                "HT_INS_COV",
            ],
            "default": "HT_SH_ACS_UNHC",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "HT_SH_ACS_UNHC",
                "HT_ADOL_UNMETMED_NOUNMET",
                "HT_ADOL_UNMETMED_TOOEXP",
                "HT_ADOL_UNMETMED_TOOFAR",
                "HT_ADOL_UNMETMED_WAITING",
                "HT_ADOL_UNMETMED_TOOEFW",
                "HT_ADOL_UNMETMED_NOTIME",
                "HT_ADOL_UNMETMED_NOKNOW",
                "HT_ADOL_UNMETMED_FEAR",
                "HT_ADOL_UNMETMED_HOPING",
                "HT_ADOL_UNMETMED_OTH",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_CH_ZS",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_PVTD_CH_ZS",
                "HT_SH_XPD_PVTD_PP_CD",
                "HT_SH_XPD_PVTD_PC_CD",
                "HT_SH_XPD_CHEX_PP_CD",
                "HT_SH_XPD_CHEX_PC_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SH_XPD_OOPC_PP_CD",
                "HT_SH_XPD_OOPC_PC_CD",
                "HT_INS_COV",
            ],
            "default_graph": "line",
            "default": "HT_SH_ACS_UNHC",
        },
    },
    "MNCH": {
        "NAME": "Maternal, newborn and child health",
        "CARDS": [
            {
                "name": "per 1,000 live births",
                "indicator": "CME_MRM0",
                "suffix": "Neonatal mortality rate",
                "min_max": True,
            },
            {
                "name": "per 1,000 live births",
                "indicator": "CME_MRY0T4",
                "suffix": "Under-5 mortality rate",
                "min_max": True,
            },
            {
                "name": "number, by sex and wealth quintile",
                "indicator": "CME_TMY0T4",
                "suffix": "Under-five deaths",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Children under-five",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "CME_MRY0T4",
                "CME_MRM0",
                "MNCH_MMR",
                "MNCH_SAB",
                "MNCH_PNCMOM",
                "CME_TMY0T4",
                "CME_SBR",
                "CME_PND",
                "HT_U5DEATH_AIDS",
                "HT_U5DEATH_DIAR",
                "HT_U5DEATH_PERT",
                "HT_U5DEATH_TETA",
                "HT_U5DEATH_MEAS",
                "HT_U5DEATH_MENI",
                "HT_U5DEATH_MALA",
                "HT_U5DEATH_PNEU",
                "HT_U5DEATH_PRET",
                "HT_U5DEATH_INTR",
                "HT_U5DEATH_SEPS",
                "HT_U5DEATH_OTHE",
                "HT_U5DEATH_CONG",
                "HT_U5DEATH_NCDS",
                "HT_U5DEATH_INJU",
                "MNCH_CSEC",
            ],
            "default": "CME_MRY0T4",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            # compare is the default selection
            "compare": "Sex",
            "default": "CME_MRY0T4",
            "indicators": [
                "CME_MRY0T4",
                "CME_MRM0",
                "MNCH_MMR",
                "MNCH_SAB",
                "MNCH_PNCMOM",
                "CME_TMY0T4",
                "CME_SBR",
                "CME_PND",
                "HT_U5DEATH_AIDS",
                "HT_U5DEATH_DIAR",
                "HT_U5DEATH_PERT",
                "HT_U5DEATH_TETA",
                "HT_U5DEATH_MEAS",
                "HT_U5DEATH_MENI",
                "HT_U5DEATH_MALA",
                "HT_U5DEATH_PNEU",
                "HT_U5DEATH_PRET",
                "HT_U5DEATH_INTR",
                "HT_U5DEATH_SEPS",
                "HT_U5DEATH_OTHE",
                "HT_U5DEATH_CONG",
                "HT_U5DEATH_NCDS",
                "HT_U5DEATH_INJU",
                "MNCH_CSEC",
            ],
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "CME_MRY0T4",
                "CME_MRM0",
                "MNCH_MMR",
                "MNCH_SAB",
                "MNCH_PNCMOM",
                "CME_TMY0T4",
                "CME_SBR",
                "CME_PND",
                "HT_U5DEATH_AIDS",
                "HT_U5DEATH_DIAR",
                "HT_U5DEATH_PERT",
                "HT_U5DEATH_TETA",
                "HT_U5DEATH_MEAS",
                "HT_U5DEATH_MENI",
                "HT_U5DEATH_MALA",
                "HT_U5DEATH_PNEU",
                "HT_U5DEATH_PRET",
                "HT_U5DEATH_INTR",
                "HT_U5DEATH_SEPS",
                "HT_U5DEATH_OTHE",
                "HT_U5DEATH_CONG",
                "HT_U5DEATH_NCDS",
                "HT_U5DEATH_INJU",
                "MNCH_CSEC",
            ],
            "default_graph": "line",
            "default": "CME_MRY0T4",
        },
    },
    "IMMUNIZATION": {
        "NAME": "Immunization",
        "CARDS": [
            {
                "name": "who received the third dose of DPT-containing vaccine",
                "indicator": "IM_DTP3",  # IM_DTP3
                "suffix": "Percentage of surviving infants",
                "min_max": True,
            },
            {
                "name": "with at least 80% DTP3 coverage",
                "indicator": "HT_DIST80DTP3_P",
                "suffix": "Percentage of districts",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Immunization of Children",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "IM_DTP3",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "IM_MCV1",
                "HT_DIST80DTP3_P",
                "HT_COVERAGE_DTP3",
            ],
            "default": "IM_DTP3",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "IM_DTP3",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "IM_MCV1",
                "HT_DIST80DTP3_P",
                "HT_COVERAGE_DTP3",
            ],
            "default": "HT_SH_ACS_PCV3",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "IM_DTP3",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "IM_MCV1",
                "HT_DIST80DTP3_P",
                "HT_COVERAGE_DTP3",
            ],
            "default_graph": "line",
            "default": "HT_DIST80DTP3_P",
        },
    },
    "NUTRITION": {
        "NAME": "Nutrition",
        "CARDS": [
            {
                "name": "Overweight by sex, age groups, residence and wealth quintile",
                "indicator": "NT_ANT_WHZ_PO2",
                "suffix": "Percent",
                "min_max": True,
            },
            {
                "name": "Stunting by sex, age groups, residence and wealth quintile",
                "indicator": "NT_ANT_HAZ_NE2",
                "suffix": "Percent",
                "min_max": True,
            },
            {
                "name": "Exclusive breastfeeding by sex, age groups, residence and wealth quintile",
                "indicator": "NT_BF_EXBF",
                "suffix": "Percent",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Nutrition facts among Children",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "NT_BW_LBW",
                "NT_BF_EIBF",
                "NT_BF_EXBF",
                "NT_CF_MAD",
                "NT_ANT_WHZ_PO2",
                "NT_ANT_HAZ_NE2",
                "HT_SN_STA_OVWGTN",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "NT_BW_UNW",
            ],
            "default": "NT_BW_LBW",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "NT_BW_LBW",
                "NT_BF_EIBF",
                "NT_BF_EXBF",
                "NT_CF_MAD",
                "NT_ANT_WHZ_PO2",
                "NT_ANT_HAZ_NE2",
                "HT_SN_STA_OVWGTN",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "NT_BW_UNW",
            ],
            "default": "NT_BW_LBW",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "NT_BW_LBW",
                "NT_BF_EIBF",
                "NT_BF_EXBF",
                "NT_CF_MAD",
                "NT_ANT_WHZ_PO2",
                "NT_ANT_HAZ_NE2",
                "HT_SN_STA_OVWGTN",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "NT_BW_UNW",
            ],
            "default_graph": "line",
            "default": "HT_SH_STA_ANEM",
        },
    },
    "ADOLESCENTS": {
        "NAME": "Adolescent health",
        "CARDS": [
            # {
            #     "name": "(10-19) popuation",
            #     "indicator": "MT_SDG_SUICIDE",  # missing
            #     "suffix": "Total Adolescent",
            # },
            {
                "name": "Adolescent birth rate",
                "indicator": "FT_SP_DYN_ADKL",
                "suffix": "per 1,000 women aged 15-19",
                "min_max": True,
            },
            {
                "name": "Suicide mortality rate, by sex",
                "indicator": "MT_SDG_SUICIDE",
                "suffix": "deaths per 100,000 population",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Adolescent health (including mental and reproductive health)",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "FT_SP_DYN_ADKL",
                "MT_SDG_SUICIDE",
                "HT_SH_FPL_MTMM",
                "HT_ADOL_MT",
                "HT_SH_PRV_SMOK",
                "HT_CDRT_SELF_HARM",
                "HT_ADOL_MEAL",
                "HT_ADOL_NO_EXCS",
                "HT_ADOL_VGRS_EXCS",
                "HT_CHLD_BODY_RGHT",
                "HT_CHLD_BODY_NO_RGHT",
                "HT_CHLD_REG_SMOK",
                "HT_CHLD_DRNK",
                "HT_ADOL_HIGH_SATS",
                "HT_ADOL_LOW_SATS",
            ],
            "default": "FT_SP_DYN_ADKL",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "FT_SP_DYN_ADKL",
                "MT_SDG_SUICIDE",
                "HT_SH_FPL_MTMM",
                "HT_ADOL_MT",
                "HT_SH_PRV_SMOK",
                "HT_CDRT_SELF_HARM",
                "HT_ADOL_MEAL",
                "HT_ADOL_NO_EXCS",
                "HT_ADOL_VGRS_EXCS",
                "HT_CHLD_BODY_RGHT",
                "HT_CHLD_BODY_NO_RGHT",
                "HT_CHLD_REG_SMOK",
                "HT_CHLD_DRNK",
                "HT_ADOL_HIGH_SATS",
                "HT_ADOL_LOW_SATS",
            ],
            "default": "FT_SP_DYN_ADKL",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "FT_SP_DYN_ADKL",
                "MT_SDG_SUICIDE",
                "HT_SH_FPL_MTMM",
                "HT_ADOL_MT",
                "HT_SH_PRV_SMOK",
                "HT_CDRT_SELF_HARM",
                "HT_ADOL_MEAL",
                "HT_ADOL_NO_EXCS",
                "HT_ADOL_VGRS_EXCS",
                "HT_CHLD_BODY_RGHT",
                "HT_CHLD_BODY_NO_RGHT",
                "HT_CHLD_REG_SMOK",
                "HT_CHLD_DRNK",
                "HT_ADOL_HIGH_SATS",
                "HT_ADOL_LOW_SATS",
            ],
            "default_graph": "line",
            "default": "FT_SP_DYN_ADKL",
        },
    },
    "HIVAIDS": {
        "NAME": "HIV and AIDS",
        "CARDS": [
            {
                "name": "per 1,000 uninfected population, by sex and age groups",
                "indicator": "HT_SH_HIV_INCD",
                "suffix": "Number of new HIV infections",
                "min_max": True,
            },
            {
                "name": "(aged 0-14 years) living with HIV",
                "indicator": "HT_SH_HIV_0014",
                "suffix": "Children",
            },
            {
                "name": "(aged 0-14 years) living with HIV and receiving antiretroviral therapy",
                "indicator": "HVA_PED_ART_CVG",
                "suffix": "Percentage of Children",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "HIV Infections among Children",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "HT_SH_HIV_INCD",
                "HVA_PMTCT_ARV_CVG",
                "HT_SH_HIV_0014",
                "HVA_EPI_LHIV_0-19",
                "HVA_EPI_LHIV_15-24",
                "HVA_EPI_INF_RT_0-14",
                "HVA_EPI_INF_RT_10-19",
                "HVA_PED_ART_NUM",
                "HVA_PED_ART_CVG",
            ],
            "default": "HT_SH_HIV_INCD",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "HT_SH_HIV_INCD",
                "HVA_PMTCT_ARV_CVG",
                "HT_SH_HIV_0014",
                "HVA_EPI_LHIV_0-19",
                "HVA_EPI_LHIV_15-24",
                "HVA_EPI_INF_RT_0-14",
                "HVA_EPI_INF_RT_10-19",
                "HVA_PED_ART_NUM",
                "HVA_PED_ART_CVG",
            ],
            "default": "HT_SH_HIV_INCD",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "HT_SH_HIV_INCD",
                "HVA_PMTCT_ARV_CVG",
                "HT_SH_HIV_0014",
                "HVA_EPI_LHIV_0-19",
                "HVA_EPI_LHIV_15-24",
                "HVA_EPI_INF_RT_0-14",
                "HVA_EPI_INF_RT_10-19",
                "HVA_PED_ART_NUM",
                "HVA_PED_ART_CVG",
            ],
            "default_graph": "line",
            "default": "HT_SH_HIV_INCD",
        },
    },
    "WASH": {
        "NAME": "Water, sanitation and hygiene",
        "CARDS": [
            {
                "name": "using safely managed drinking water services (%, by residence)",
                "indicator": "WS_PPL_W-SM",
                "suffix": "Proportion of population",
                "min_max": True,
            },
            {
                "name": "using safely managed sanitation services (%, by residence)",
                "indicator": "WS_PPL_S-SM",
                "suffix": "Proportion of population",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "Water, sanitation and hygiene",
            "geo": "Geographic area",
            "options": dict(
                lat="latitude",
                lon="longitude",
                size="OBS_VALUE",
                text="Geographic area",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                size_max=40,
                zoom=2.5,
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "WS_PPL_W-SM",
                "WS_PPL_S-SM",
                "WS_PPL_H-B",
                "WS_PPS_S-OD",
                "HT_NO_BTH_SHW_FLSH",
            ],
            "default": "WS_PPL_W-SM",
        },
        "AREA_1": {
            "type": "bar",
            "options": dict(
                x="Geographic area",
                y="OBS_VALUE",
                barmode="group",
                text="TIME_PERIOD",
            ),
            "compare": "Sex",
            "indicators": [
                "WS_PPL_W-SM",
                "WS_PPL_S-SM",
                "WS_PPL_H-B",
                "WS_PPS_S-OD",
                "HT_NO_BTH_SHW_FLSH",
            ],
            "default": "WS_PPL_W-SM",
        },
        "AREA_2": {
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        text="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "WS_PPL_W-SM",
                "WS_PPL_S-SM",
                "WS_PPL_H-B",
                "WS_PPS_S-OD",
                "HT_NO_BTH_SHW_FLSH",
            ],
            "default_graph": "line",
            "default": "WS_PPL_W-SM",
        },
    },
}


def get_layout(**kwargs):
    kwargs["indicators"] = indicators_dict
    return get_base_layout(**kwargs)
