import dash_core_components as dcc
import dash_html_components as html
import dash_bootstrap_components as dbc
from dash.dependencies import Input, State, Output
from .base_page import get_base_layout, geo_json_countries
import plotly.express as px

indicators_dict = {
    "ECD": {
        "NAME": "ECD",
        "CARDS": [
            {
                "name": "of children as a share of total population",
                "indicator": "DM_CHLD_POP_PT",
                "suffix": "Percentage range among countries",
                "min_max": True,
            },
            {
                "name": "Government expenditure on education (% of GDP)",
                "indicator": "EDU_FIN_EXP_PT_GDP",
                "suffix": "Percentage range among countries",
                "min_max": True,
            },
        ],
        "MAIN": {
            "name": "ECD",
            "geo": "Geographic area",
            "options": dict(
                geojson=geo_json_countries,
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 62.995158, "lon": 88.048713},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Geographic area": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Geographic area": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "EDU_FIN_EXP_PT_GDP",
                "EDU_SDG_COMP_EDU_L02",
                "EDU_SDG_COMP_FREE_L02",
                "EDU_SDG_GER_L01",
                "EDUNF_GER_L02",
                "EDU_ECEC_PART",
                "EDUNF_NERA_L1_UNDER1",
                "EDUNF_NARA_L1_UNDER1",
                "PT_CHLD_INRESIDENTIAL",
                "PT_CHLD_INRESIDENTIAL_RATE_B",
                "PT_F_15-49_W-BTNG",
                "PT_M_15-49_W-BTNG",
                "PT_CHLD_1-14_PS-PSY-V_CGVR",
                "PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH",
                "VC_VOV_PHYL",
                "VC_VOV_SEXL",
                "VC_VOV_ROBB",
                "VC_SNS_WALN",
                "PT_F_GE15_SX_V_PTNR_12MNTH",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_CHEX_PC_CD",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_GHED_GD_ZS",
                "IM_DTP3",
                "IM_MCV1",
                "HT_DIST80DTP3_P",
                "MNCH_MMR",
                "CME_PND",
                "CME_MRM0",
                "CME_TRY0T4",
                "CME_MRY0T4",
                "CME_SBR",
                "HT_SN_STA_OVWGTN",
                "NT_BF_EXBF",
                "NT_BW_LBW",
                "FT_BRTS_LIVE_LOW",
                "FT_BRTS_LIVE_LOWRT",
                "NT_BW_UNW",
                "NT_ANT_WHZ_PO2",
                "NT_ANT_HAZ_NE2",
                "WS_PPL_W-SM",
                "WS_PPL_S-SM",
                "PV_SI_POV_UMIC",
                "PV_AROPE",
                "PV_WB_SI_POV_NAHC",
                "PV_SD_MDP_ANDI",
                "PV_SD_MDP_CSMP",
                "PV_SD_MDP_MUHC",
                "PV_SD_MDP_MUHHC",
                "PV_SDG_SI_POV_NAHC",
                "PV_SI_POV_DAY1",
                "PV_SI_POV_EMP1",
                "DM_CHLD_POP_PT",
                "DM_CHLD_POP",
                "DM_FRATE_TOT",
                "EC_GII",
                "EC_SI_POV_GINI",
                "EC_NY_GNP_ATLS_CD",
                "EC_NY_GNP_PCAP_CD",
                "EC_HDI",
                "EDU_FIN_EXP_PT_GDP",
                "EC_SL_UEM_TOTL_NE_ZS",
                "EC_SL_UEM_TOTL_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_SP_GOV_EXP_TOT",
            ],
            "default": "CME_MRM0",
        },
        "AREA_1": {
            "name": "Education",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Age",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "indicators": [
                "EDU_FIN_EXP_PT_GDP",
                "EDU_SDG_COMP_EDU_L02",
                "EDU_SDG_COMP_FREE_L02",
                "EDU_SDG_GER_L01",
                "EDUNF_GER_L02",
                "EDU_ECEC_PART",
                "EDUNF_NERA_L1_UNDER1",
                "EDUNF_NARA_L1_UNDER1",
            ],
            "default": "EDU_FIN_EXP_PT_GDP",
        },
        "AREA_2": {
            "name": "Family Environment and Protection",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Age",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PT_CHLD_INRESIDENTIAL",
                "PT_CHLD_INRESIDENTIAL_RATE_B",
                "PT_F_15-49_W-BTNG",
                "PT_M_15-49_W-BTNG",
                "PT_CHLD_1-14_PS-PSY-V_CGVR",
                "PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH",
                "VC_VOV_PHYL",
                "VC_VOV_SEXL",
                "VC_VOV_ROBB",
                "VC_SNS_WALN",
                "PT_F_GE15_SX_V_PTNR_12MNTH",
            ],
            "default_graph": "line",
            "default": "PT_F_GE15_SX_V_PTNR_12MNTH",
        },
        "AREA_3": {
            "name": "Health and Nutrition",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Age",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_CHEX_PC_CD",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_GHED_GD_ZS",
                "IM_DTP3",
                "IM_MCV1",
                "HT_DIST80DTP3_P",
                "MNCH_MMR",
                "CME_PND",
                "CME_MRM0",
                "CME_TRY0T4",
                "CME_MRY0T4",
                "CME_SBR",
                "HT_SN_STA_OVWGTN",
                "NT_BF_EXBF",
                "NT_BW_LBW",
                "FT_BRTS_LIVE_LOW",
                "FT_BRTS_LIVE_LOWRT",
                "NT_BW_UNW",
                "NT_ANT_WHZ_PO2",
                "NT_ANT_HAZ_NE2",
                "WS_PPL_W-SM",
                "WS_PPL_S-SM",
            ],
            "default_graph": "bar",
            "default": "HT_SH_XPD_CHEX_GD_ZS",
        },
        "AREA_4": {
            "name": "Poverty",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Age",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PV_SI_POV_UMIC",
                "PV_AROPE",
                "PV_WB_SI_POV_NAHC",
                "PV_SD_MDP_ANDI",
                "PV_SD_MDP_CSMP",
                "PV_SD_MDP_MUHC",
                "PV_SD_MDP_MUHHC",
                "PV_SDG_SI_POV_NAHC",
                "PV_SI_POV_DAY1",
                "PV_SI_POV_EMP1",
            ],
            "default_graph": "bar",
            "default": "PV_SI_POV_UMIC",
        },
        "AREA_5": {
            "name": "Child Rights Landscape",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Age",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "DM_CHLD_POP_PT",
                "DM_CHLD_POP",
                "DM_FRATE_TOT",
                "EC_GII",
                "EC_SI_POV_GINI",
                "EC_NY_GNP_ATLS_CD",
                "EC_NY_GNP_PCAP_CD",
                "EC_HDI",
                "EDU_FIN_EXP_PT_GDP",
                "EC_SL_UEM_TOTL_NE_ZS",
                "EC_SL_UEM_TOTL_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_SP_GOV_EXP_TOT",
            ],
            "default_graph": "bar",
            "default": "DM_CHLD_POP_PT",
        },
        # "AREA_6": {
        #     "name": "Participation",
        #     "graphs": {
        #         "bar": {
        #             "options": dict(
        #                 x="Geographic area",
        #                 y="OBS_VALUE",
        #                 barmode="group",
        #                 # text="TIME_PERIOD",
        #                 text="OBS_VALUE",
        #                 hover_name="TIME_PERIOD",
        #             ),
        #             "compare": "Age",
        #         },
        #         "line": {
        #             "options": dict(
        #                 x="TIME_PERIOD",
        #                 y="OBS_VALUE",
        #                 color="Geographic area",
        #                 hover_name="Geographic area",
        #                 line_shape="spline",
        #                 render_mode="svg",
        #             ),
        #             "trace_options": dict(mode="lines+markers"),
        #         },
        #     },
        #     "indicators": [],
        #     "default_graph": "bar",
        #     "default": "",
        # },
    },
}

main_title = "ECD"


def get_layout(**kwargs):
    kwargs["indicators"] = indicators_dict
    kwargs["main_title"] = main_title
    return get_base_layout(**kwargs)
