import pandas as pd

import plotly.express as px

from . import data, years
from .base_page import get_base_layout, geo_json_countries

indicators_dict = {
    "EDUCATION": {
        "NAME": "Education",
        "CARDS": [
            {
                "name": "Card Unit",
                "indicator": "",
                "suffix": "Card Name",
                # "absolute": True,
                "min_max": True,
            },
            # {
            #     "name": "People at risk of poverty or social exclusion",
            #     "indicator": "PV_AROPE",
            #     "suffix": "Percentage range among countries",
            #     # "absolute": True,
            #     "min_max": True,
            # },
        ],
        "MAIN": {
            "name": "Education",
            "geo": "Geographic area",
            "options": dict(
                geojson=geo_json_countries,
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 48.3794, "lon": 31.1656},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Geographic area": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Geographic area": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PV_SI_POV_EMP1",
                "PV_SI_POV_DAY1",
                "PV_SI_POV_UMIC",
                "PV_SDG_SI_POV_NAHC",
                "PV_WB_SI_POV_NAHC",
                "PV_AROPE",
                "PV_AROPRT",
                "PV_SD_MDP_CSMP",
                "PV_SD_MDP_MUHHC",
                "PV_SD_MDP_MUHC",
                "PV_SI_POV_MDIM",
                "PV_SI_POV_MDIM_17",
                "WS_PPL_W-B",
                "WS_PPL_S-B",
                "PV_SEV_MAT_DPRT",
            ],
            "default": "PV_SEV_MAT_DPRT",
        },
        "AREA_1": {
            "name": "Participation",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "indicators": [
                "EDUNF_ROFST_L1",
                "EDUNF_ROFST_L2",
                "EDUNF_ROFST_L3",
                "EDUNF_OFST_L1",
                "EDUNF_OFST_L2",
                "EDUNF_OFST_L3",
                "EDUNF_STU_L1_TOT",
                "EDUNF_STU_L2_TOT",
                "EDUNF_STU_L3_TOT",
                "EDUNF_GER_L2_GEN",
                "EDUNF_GER_L2_VOC",
                "EDUNF_GER_L3",
                "EDUNF_GER_L3_GEN",
                "EDUNF_GER_L3_VOC",
                "EDUNF_NER_L02",
                "EDUNF_NERA_L1_UNDER1",
                "EDUNF_NERA_L1",
                "EDUNF_NERA_L2",
                "EDUNF_GER_L1",
                "EDUNF_GER_L2",
                "EDUNF_GER_L3",
                "EDUNF_NIR_L1_ENTRYAGE",
                "EDUNF_TRANRA_L2",
                "EDU_SDG_SCH_L1",
                "EDU_SDG_SCH_L2",
                "EDU_SDG_SCH_L3",
                "WS_SCH_H-B",
                "WS_SCH_S-B",
                "WS_SCH_W-B",
                "EDU_CHLD_DISAB",
                "EDU_CHLD_DISAB_GENERAL",
                "EDU_CHLD_DISAB_SPECIAL",
                "EDUNF_CR_L1",
                "EDUNF_CR_L2",
                "EDUNF_CR_L3",
                "EDUNF_DR_L1",
                "EDUNF_DR_L2",
            ],
            "default": "EDUNF_ROFST_L1",
        },
        "AREA_2": {
            "name": "Learning Quality",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "EDU_PISA_MAT",
                "EDU_PISA_REA",
                "EDU_PISA_SCI",
                "ECD_CHLD_36-59M_LMPSL",
                "EDU_SDG_STU_L2_GLAST_MAT",
                "EDU_SDG_STU_L2_GLAST_REA",
                "EDU_SDG_STU_L1_GLAST_MAT",
                "EDU_SDG_STU_L1_G2OR3_MAT",
                "EDU_SDG_STU_L1_GLAST_REA",
                "EDU_SDG_STU_L1_G2OR3_REA",
                "EDUNF_LR_YOUTH",
                "EDUNF_LR_ADULT",
                "EDU_SDG_TRTP_L02",
                "EDU_SDG_TRTP_L1",
                "EDU_SDG_TRTP_L2",
                "EDU_SDG_TRTP_L3",
                "EDU_SDG_QUTP_L02",
                "EDU_SDG_QUTP_L1",
                "EDU_SDG_QUTP_L2",
                "EDU_SDG_QUTP_L3",
            ],
            "default_graph": "line",
            "default": "EDU_PISA_MAT",
        },
        "AREA_3": {
            "name": "Governance",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "EDU_FIN_EXP_PT_GDP",
                "EDU_FIN_EXP_PT_TOT",
                "EDU_SDG_FREE_EDU_L02",
                "EDU_SDG_COMP_EDU_L02",
                "EDUNF_PRP_L02",
                "EDUNF_PRP_L1",
                "EDUNF_PRP_L2",
                "EDUNF_PRP_L3",
                "EDUNF_STU_L01_PUB",
                "EDUNF_STU_L02_PUB",
                "EDUNF_STU_L1_PUB",
                "EDUNF_STU_L2_PUB",
                "EDUNF_STU_L3_PUB",
                "EDUNF_STU_L01_PRV",
                "EDUNF_STU_L02_PRV",
                "EDUNF_STU_L1_PRV",
                "EDUNF_STU_L2_PRV",
                "EDUNF_STU_L3_PRV",
                "EDU_FIN_EXP_L02",
                "EDU_FIN_EXP_L1",
                "EDU_FIN_EXP_L2",
                "EDU_FIN_EXP_L3",
                "EDU_FIN_EXP_L4",
                "EDU_FIN_EXP_L5T8",
                "EDUNF_ADMIN_L1_GLAST_REA",
                "EDUNF_ADMIN_L1_GLAST_MAT",
                "EDUNF_ADMIN_L2_REA",
                "EDUNF_ADMIN_L2_MAT",
                "EDUNF_ADMIN_L1_G2OR3_REA",
                "EDUNF_ADMIN_L1_G2OR3_MAT",
            ],
            "default_graph": "bar",
            "default": "EDUNF_STU_L01_PUB",
        },
    },
    "PROTECTION": {
        "NAME": "Family Environment and Protection",
        "CARDS": [
            {
                "name": "Card Unit",
                "indicator": "",
                "suffix": "Card Name",
                # "absolute": True,
                "min_max": True,
            },
            # {
            #     "name": "Adults who think that physical punishment is necessary to raise/educate children",
            #     "indicator": "PT_ADLT_PS_NEC",
            #     "suffix": "Percentage range among countries",
            #     "min_max": True,
            # },
            # {
            #     "name": "Women age 20-24 years married or in union before age 18",
            #     "indicator": "PT_F_20-24_MRD_U18",
            #     "suffix": "Percentage range among countries",
            #     "min_max": True,
            # },
            # {
            #     "name": "Men age 20-24 years married or in union before age 18",
            #     "indicator": "PT_M_20-24_MRD_U18",
            #     "suffix": "Percentage range among countries",
            #     "min_max": True,
            # },
        ],
        "MAIN": {
            "name": "Family Environment and Protection",
            "geo": "Geographic area",
            "options": dict(
                geojson=geo_json_countries,
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 48.3794, "lon": 31.1656},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Geographic area": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Geographic area": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PV_SI_COV_BENFTS",
                "PV_SI_COV_LMKT",
                "PV_SI_COV_SOCAST",
                "PV_SI_COV_SOCINS",
                "PV_SI_COV_WKINJRY",
                "PV_SI_COV_CHLD",
                "PV_SI_COV_DISAB",
                "PV_SI_COV_MATNL",
                "PV_SI_COV_POOR",
                "PV_SI_COV_UEMP",
                "PV_SI_COV_VULN",
                "PV_SI_COV_PENSN",
            ],
            "default": "PV_SI_COV_BENFTS",
        },
        "AREA_1": {
            "name": "Violence against Children and Women",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "default": "PT_ADLT_PS_NEC",
            "indicators": [
                "PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH",
                "PT_F_GE15_SX_V_PTNR_12MNTH",
                "PT_VC_VOV_PHYL",
                "PT_VC_VOV_SEXL",
                "PT_VC_VOV_ROBB",
                "PT_VC_SNS_WALN",
                "PT_CHLD_1-14_PS-PSY-V_CGVR",
                "PT_F_18-29_SX-V_AGE-18",
                "PT_M_18-29_SX-V_AGE-18",
                "PT_VC_PRR_PHYV",
                "PT_VC_PRR_SEXV",
                "PT_VC_PRR_ROBB",
                "PT_ADLT_PS_NEC",
                "PT_F_15-49_W-BTNG",
                "PT_M_15-49_W-BTNG",
                "PT_ST_13-15_BUL_30-DYS",
            ],
        },
        "AREA_2": {
            "name": "Children without parental care",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PT_CHLD_INRESIDENTIAL",
                "PT_CHLD_INRESIDENTIAL_RATE_B",
                "PT_CHLD_DISAB_PUBLIC",
                "PT_CHLD_LEFTRESCARE",
                "PT_CHLD_LEFTRESCARE_RETURNED",
                "PT_CHLD_LEFTRESCARE_INFAMILY",
                "PT_CHLD_LEFTRESCARE_ADOPTED",
                "PT_CHLD_LEFTRESCARE_INDEPENDENT",
                "PT_CHLD_LEFTRESCARE_TRANSFERED",
                "PT_CHLD_LEFTRESCARE_DIED",
                "PT_CHLD_LEFTRESCARE_OTHER",
                "PT_CHLD_CARED_BY_FOSTER",
                "PT_CHLD_CARED_BY_FOSTER_RATE",
                "PT_CHLD_DISAB_FOSTER",
                "PT_CHLD_CARED_GUARDIAN",
                "PT_CHLD_CARED_GUARDIAN_RATE",
                "PT_CHLD_DISAB_CARED_GUARDIAN",
                "PT_CHLD_GUARDIAN",
                "PT_CHLD_ENTEREDFOSTER",
                "PT_CHLD_ADOPTION",
                "PT_CHLD_ADOPTION_RATE",
                "PT_CHLD_ADOPTION_DISAB",
                "PT_CHLD_ADOPTION_AVAILABLE",
                "PT_CHLD_ADOPTION_AVAILABLE_DISAB",
            ],
            "default_graph": "line",
            "default": "PT_CHLD_INRESIDENTIAL",
        },
        "AREA_3": {
            "name": "Juvenile Justice",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "JJ_CHLD_DETENTION",
                "JJ_CHLD_CONVICTED",
                "JJ_CHLD_SENTENCERT",
                "JJ_VC_PRS_UNSNT",
                "JJ_PRISIONERS",
                "JJ_PRISIONERS_RT",
            ],
            "default_graph": "bar",
            "default": "JJ_CHLD_CONVICTED",
        },
        "AREA_4": {
            "name": "Child Marriage and Labour",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PT_F_15-19_MRD",
                "PT_M_15-19_MRD",
                "PT_F_20-24_MRD_U15",
                "PT_F_20-24_MRD_U18",
                "PT_M_20-24_MRD_U18",
                "PT_CHLD_5-17_LBR_ECON",
                "PT_CHLD_5-17_LBR_ECON-HC",
            ],
            "default_graph": "bar",
            "default": "PT_CHLD_5-17_LBR_ECON",
        },
    },
    "HEALTH": {
        "NAME": "Health and Nutrition",
        "CARDS": [
            {
                "name": "Card Unit",
                "indicator": "",
                "suffix": "Card Name",
                # "absolute": True,
                "min_max": True,
            },
            # {
            #     "name": "Children/households receiving child/family cash benefits",
            #     "indicator": "PV_SI_COV_CHLD",
            #     "suffix": "Percentage range among countries",
            #     "abosolute": True,
            #     "min_max": True,
            # },
        ],
        "MAIN": {
            "name": "Health and Nutrition",
            "geo": "Geographic area",
            "options": dict(
                geojson=geo_json_countries,
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 48.3794, "lon": 31.1656},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Geographic area": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Geographic area": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PV_SI_COV_BENFTS",
                "PV_SI_COV_LMKT",
                "PV_SI_COV_SOCAST",
                "PV_SI_COV_SOCINS",
                "PV_SI_COV_WKINJRY",
                "PV_SI_COV_CHLD",
                "PV_SI_COV_DISAB",
                "PV_SI_COV_MATNL",
                "PV_SI_COV_POOR",
                "PV_SI_COV_UEMP",
                "PV_SI_COV_VULN",
                "PV_SI_COV_PENSN",
            ],
            "default": "PV_SI_COV_BENFTS",
        },
        "AREA_1": {
            "name": "Health System",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "default": "HT_ADOL_UNMETMED_FEAR",
            "indicators": [
                "HT_SH_ACS_UNHC",
                "HT_ADOL_UNMETMED_NOUNMET",
                "HT_ADOL_UNMETMED_TOOEXP",
                "HT_ADOL_UNMETMED_TOOFAR",
                "HT_ADOL_UNMETMED_WAITING",
                "HT_ADOL_UNMETMED_TOOEFW",
                "HT_ADOL_UNMETMED_NOTIME",
                "HT_ADOL_UNMETMED_NOKNOW",
                "HT_ADOL_UNMETMED_FEAR",
                "HT_ADOL_UNMETMED_HOPING",
                "HT_ADOL_UNMETMED_OTH",
                "HT_SH_XPD_CHEX_GD_ZS",
                "HT_SH_XPD_GHED_GD_ZS",
                "HT_SH_XPD_GHED_GE_ZS",
                "HT_SH_XPD_GHED_CH_ZS",
                "HT_SH_XPD_GHED_PP_CD",
                "HT_SH_XPD_GHED_PC_CD",
                "HT_SH_XPD_PVTD_CH_ZS",
                "HT_SH_XPD_PVTD_PP_CD",
                "HT_SH_XPD_PVTD_PC_CD",
                "HT_SH_XPD_CHEX_PP_CD",
                "HT_SH_XPD_CHEX_PC_CD",
                "HT_SH_XPD_OOPC_CH_ZS",
                "HT_SH_XPD_OOPC_PP_CD",
                "HT_SH_XPD_OOPC_PC_CD",
                "HT_INS_COV",
            ],
        },
        "AREA_2": {
            "name": "Maternal, Newborn, Child health + Immunization",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "CME_MRY0T4",
                "CME_MRM0",
                "MNCH_MMR",
                "MNCH_SAB",
                "MNCH_PNCMOM",
                "CME_TMY0T4",
                "CME_SBR",
                "CME_PND",
                "HT_U5DEATH_AIDS",
                "HT_U5DEATH_DIAR",
                "HT_U5DEATH_PERT",
                "HT_U5DEATH_TETA",
                "HT_U5DEATH_MEAS",
                "HT_U5DEATH_MENI",
                "HT_U5DEATH_MALA",
                "HT_U5DEATH_PNEU",
                "HT_U5DEATH_PRET",
                "HT_U5DEATH_INTR",
                "HT_U5DEATH_SEPS",
                "HT_U5DEATH_OTHE",
                "HT_U5DEATH_CONG",
                "HT_U5DEATH_NCDS",
                "HT_U5DEATH_INJU",
                "MNCH_CSEC",
                "MNCH_PNCMOM",
                "IM_DTP3",
                "HT_SH_ACS_DTP3",
                "HT_SH_ACS_HPV",
                "HT_SH_ACS_MCV2",
                "HT_SH_ACS_PCV3",
                "IM_MCV1",
                "HT_DIST80DTP3_P",
                "HT_COVERAGE_DTP3",
            ],
            "default_graph": "line",
            "default": "CME_MRY0T4",
        },
        "AREA_3": {
            "name": "Nutrition + Adolescent Health",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "default": "HT_ADOL_MT",
            "indicators": [
                "NT_BW_LBW",
                "NT_BF_EIBF",
                "NT_BF_EXBF",
                "NT_CF_MAD",
                "NT_ANT_WHZ_PO2",
                "NT_ANT_HAZ_NE2",
                "HT_SN_STA_OVWGTN",
                "HT_SH_STA_ANEM",
                "HT_SH_STA_ANEM_NPRG",
                "HT_SH_STA_ANEM_PREG",
                "NT_BW_UNW",
                "FT_SP_DYN_ADKL",
                "MT_SDG_SUICIDE",
                "HT_SH_FPL_MTMM",
                "HT_ADOL_MT",
                "HT_SH_PRV_SMOK",
                "HT_CDRT_SELF_HARM",
                "HT_ADOL_MEAL",
                "HT_ADOL_NO_EXCS",
                "HT_ADOL_VGRS_EXCS",
                "HT_CHLD_BODY_RGHT",
                "HT_CHLD_BODY_NO_RGHT",
                "HT_CHLD_REG_SMOK",
                "HT_CHLD_DRNK",
                "HT_ADOL_HIGH_SATS",
                "HT_ADOL_LOW_SATS",
            ],
        },
        "AREA_4": {
            "name": "HIV and AIDS + Water, Sanitation and Hygiene",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "default": "HT_SH_HIV_INCD",
            "indicators": [
                "HT_SH_HIV_INCD",
                "HVA_PMTCT_ARV_CVG",
                "HT_SH_HIV_0014",
                "HVA_EPI_LHIV_0-19",
                "HVA_EPI_LHIV_15-24",
                "HVA_EPI_INF_RT_0-14",
                "HVA_EPI_INF_RT_10-19",
                "HVA_PED_ART_NUM",
                "HVA_PED_ART_CVG",
                "WS_PPL_W-SM",
                "WS_PPL_S-SM",
                "WS_PPL_H-B",
                "WS_PPS_S-OD",
                "HT_NO_BTH_SHW_FLSH",
            ],
        },
    },
    "POVERTY": {
        "NAME": "Poverty",
        "CARDS": [
            {
                "name": "Card Unit",
                "indicator": "",
                "suffix": "Card Name",
                # "absolute": True,
                "min_max": True,
            },
            # {
            #     "name": "Children/households receiving child/family cash benefits",
            #     "indicator": "PV_SI_COV_CHLD",
            #     "suffix": "Percentage range among countries",
            #     "abosolute": True,
            #     "min_max": True,
            # },
        ],
        "MAIN": {
            "name": "Poverty",
            "geo": "Geographic area",
            "options": dict(
                geojson=geo_json_countries,
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 48.3794, "lon": 31.1656},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Geographic area": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Geographic area": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PV_SI_COV_BENFTS",
                "PV_SI_COV_LMKT",
                "PV_SI_COV_SOCAST",
                "PV_SI_COV_SOCINS",
                "PV_SI_COV_WKINJRY",
                "PV_SI_COV_CHLD",
                "PV_SI_COV_DISAB",
                "PV_SI_COV_MATNL",
                "PV_SI_COV_POOR",
                "PV_SI_COV_UEMP",
                "PV_SI_COV_VULN",
                "PV_SI_COV_PENSN",
            ],
            "default": "PV_SI_COV_BENFTS",
        },
        "AREA_1": {
            "name": "Poverty and multi-dimensional deprivation",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "default": "PV_AROPE",
            "indicators": [
                "PV_SI_POV_EMP1",
                "PV_SI_POV_DAY1",
                "PV_SI_POV_UMIC",
                "PV_SDG_SI_POV_NAHC",
                "PV_WB_SI_POV_NAHC",
                "PV_AROPE",
                "PV_AROPRT",
                "PV_SD_MDP_CSMP",
                "PV_SD_MDP_MUHHC",
                "PV_SD_MDP_MUHC",
                "PV_SI_POV_MDIM",
                "PV_SI_POV_MDIM_17",
                "WS_PPL_W-B",
                "WS_PPL_S-B",
                "PV_SEV_MAT_DPRT",
            ],
        },
        "AREA_2": {
            "name": "Social protection system",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PV_SI_COV_BENFTS",
                "PV_SI_COV_LMKT",
                "PV_SI_COV_SOCAST",
                "PV_SI_COV_SOCINS",
                "PV_SI_COV_WKINJRY",
                "PV_SI_COV_CHLD",
                "PV_SI_COV_DISAB",
                "PV_SI_COV_MATNL",
                "PV_SI_COV_POOR",
                "PV_SI_COV_UEMP",
                "PV_SI_COV_VULN",
                "PV_SI_COV_PENSN",
            ],
            "default_graph": "line",
            "default": "PV_SI_COV_BENFTS",
        },
    },
    "RIGHTS": {
        "NAME": "Child Rights Landscape",
        "CARDS": [
            {
                "name": "Card Unit",
                "indicator": "",
                "suffix": "Card Name",
                # "absolute": True,
                "min_max": True,
            },
            # {
            #     "name": "Children/households receiving child/family cash benefits",
            #     "indicator": "PV_SI_COV_CHLD",
            #     "suffix": "Percentage range among countries",
            #     "abosolute": True,
            #     "min_max": True,
            # },
        ],
        "MAIN": {
            "name": "Child Rights Landscape",
            "geo": "Geographic area",
            "options": dict(
                geojson=geo_json_countries,
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 48.3794, "lon": 31.1656},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Geographic area": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Geographic area": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PV_SI_COV_BENFTS",
                "PV_SI_COV_LMKT",
                "PV_SI_COV_SOCAST",
                "PV_SI_COV_SOCINS",
                "PV_SI_COV_WKINJRY",
                "PV_SI_COV_CHLD",
                "PV_SI_COV_DISAB",
                "PV_SI_COV_MATNL",
                "PV_SI_COV_POOR",
                "PV_SI_COV_UEMP",
                "PV_SI_COV_VULN",
                "PV_SI_COV_PENSN",
            ],
            "default": "PV_SI_COV_BENFTS",
        },
        "AREA_1": {
            "name": "Demography about Children",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "default": "DM_FRATE_TOT",
            "indicators": [
                "DM_CHLD_TWO_PRNT",
                "DM_FRATE_TOT",
            ],
        },
        "AREA_2": {
            "name": "Political Economy",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "EC_HDI",
                "EC_NY_GDP_MKTP_KD_ZG",
                "EC_NY_GDP_PCAP_KD_ZG",
                "EC_NE_DAB_TOTL_ZS",
                "EC_TEC_GRL_GOV_EXP",
                "EC_TEC_CNT_GOV_EXP",
                "EC_TEC_STA_GOV_EXP",
                "EC_TEC_LOC_GOV_EXP",
                "EC_TEC_SSF_EXP",
                "EC_GR_G14_GDP",
                "EDU_FIN_EXP_PT_GDP",
                "HT_SH_XPD_GHED_GD_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_SP_GOV_EXP_TOT",
                "EC_NY_GDP_PCAP_PP_CD",
                "EC_NY_GNP_ATLS_CD",
                "EC_NY_GNP_PCAP_CD",
                "EC_GC_DOD_TOTL_GD_ZS",
                "EC_SI_POV_GINI",
                "EC_SL_UEM_TOTL_NE_ZS",
            ],
            "default_graph": "line",
            "default": "EC_HDI",
        },
        "AREA_3": {
            "name": "Migration and Displacement + Risks, Humanitarian Situation and impact of climate change",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "default": "DM_POP_NETM",
            "indicators": [
                "DM_POP_NETM",
                "DM_SM_POP_REFG",
                "DM_SM_POP_REFG_OR",
                "DM_ASYL_FRST",
                "DM_ASYL_UASC",
                "MG_INTNL_MG_CNTRY_DEST_PS",
                "CR_VC_DSR_MTMP",
                "CR_VC_DSR_DAFF",
                "CR_SH_STA_AIRP",
                "CR_SH_STA_ASAIRP",
                "CR_EG_EGY_CLEAN",
                "CR_EG_ACS_ELEC",
                "CR_SG_DSR_LGRGSR",
            ],
        },
        "AREA_4": {
            "name": "Data and Public spending on Children",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "line",
            "default": "EC_TOT_PUB_EXP_TOT",
            "indicators": [
                "EDU_FIN_EXP_PT_GDP",
                "HT_SH_XPD_GHED_GD_ZS",
                "EC_SP_GOV_EXP_GDP",
                "EC_TOT_PUB_EXP_GDP",
                "EC_TOT_PUB_EXP_TOT",
                "EC_FAM_PUB_EXP_GDP",
                "EC_FAM_PUB_EXP_TOT",
                "CR_IQ_SCI_OVRL",
                "CR_SG_STT_FPOS",
                "CR_SG_STT_NSDSFND",
                "CR_SG_STT_NSDSIMPL",
                "CR_SG_STT_NSDSFDGVT",
                "CR_SG_STT_NSDSFDDNR",
                "CR_SG_STT_NSDSFDOTHR",
                "CR_SG_STT_CAPTY",
                "CR_SG_REG_CENSUSN",
            ],
        },
    },
    "PARTICIPATION": {
        "NAME": "Participation",
        "CARDS": [
            {
                "name": "Card Unit",
                "indicator": "",
                "suffix": "Card Name",
                # "absolute": True,
                "min_max": True,
            },
            # {
            #     "name": "Children/households receiving child/family cash benefits",
            #     "indicator": "PV_SI_COV_CHLD",
            #     "suffix": "Percentage range among countries",
            #     "abosolute": True,
            #     "min_max": True,
            # },
        ],
        "MAIN": {
            "name": "Participation",
            "geo": "Geographic area",
            "options": dict(
                geojson=geo_json_countries,
                locations="REF_AREA",
                featureidkey="id",
                color="OBS_VALUE",
                color_continuous_scale=px.colors.sequential.GnBu,
                mapbox_style="carto-positron",
                zoom=2,
                center={"lat": 48.3794, "lon": 31.1656},
                opacity=0.5,
                labels={
                    "OBS_VALUE": "Value",
                    "Geographic area": "Country",
                    "TIME_PERIOD": "Year",
                    "REF_AREA": "ISO3 Code",
                },
                hover_data={
                    "OBS_VALUE": True,
                    "REF_AREA": False,
                    "Geographic area": True,
                    "TIME_PERIOD": True,
                },
                animation_frame="TIME_PERIOD",
                height=750,
            ),
            "indicators": [
                "PV_SI_COV_BENFTS",
                "PV_SI_COV_LMKT",
                "PV_SI_COV_SOCAST",
                "PV_SI_COV_SOCINS",
                "PV_SI_COV_WKINJRY",
                "PV_SI_COV_CHLD",
                "PV_SI_COV_DISAB",
                "PV_SI_COV_MATNL",
                "PV_SI_COV_POOR",
                "PV_SI_COV_UEMP",
                "PV_SI_COV_VULN",
                "PV_SI_COV_PENSN",
            ],
            "default": "PV_SI_COV_BENFTS",
        },
        "AREA_1": {
            "name": "Birth registration and documentation",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "default_graph": "bar",
            "default": "PT_CHLD_Y0T4_REG",
            "indicators": [
                "PT_CHLD_Y0T4_REG",
                "PP_SG_REG_BRTH90N",
                "PP_SG_REG_DETH75N",
            ],
        },
        "AREA_2": {
            "name": "Access to Justice",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PP_SG_NHR_IMPLN",
                "PP_SG_NHR_INTEXSTN",
                "PP_SG_NHR_NOSTUSN",
                "PP_SG_NHR_NOAPPLN",
                "JJ_CHLD_CRIME",
                "JJ_CHLD_CRIMERT",
            ],
            "default_graph": "line",
            "default": "JJ_CHLD_CRIME",
        },
        "AREA_3": {
            "name": "Information, Internet and Right to privacy",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PP_IT_USE_ii99",
                "PP_SE_ADT_ACTS_ATCH",
                "PP_SE_ADT_ACTS_CPT",
                "PP_SE_ADT_ACTS_CDV",
                "PP_SE_ADT_ACTS_SSHT",
                "PP_SE_ADT_ACTS_PRGM",
                "PP_SE_ADT_ACTS_PST",
                "PP_SE_ADT_ACTS_SFWR",
                "PP_SE_ADT_ACTS_TRFF",
                "PP_SE_ADT_ACTS_CMFL",
                "PP_IT_MOB_OWN",
            ],
            "default_graph": "line",
            "default": "PP_SE_ADT_ACTS_ATCH",
        },
        "AREA_4": {
            "name": "Leisure and Culture",
            "graphs": {
                "bar": {
                    "options": dict(
                        x="Geographic area",
                        y="OBS_VALUE",
                        barmode="group",
                        # text="TIME_PERIOD",
                        text="OBS_VALUE",
                        hover_name="TIME_PERIOD",
                    ),
                    "compare": "Sex",
                },
                "line": {
                    "options": dict(
                        x="TIME_PERIOD",
                        y="OBS_VALUE",
                        color="Geographic area",
                        hover_name="Geographic area",
                        line_shape="spline",
                        render_mode="svg",
                    ),
                    "trace_options": dict(mode="lines+markers"),
                },
            },
            "indicators": [
                "PP_ADOL_TVGM",
                "PP_ADOL_INET",
                "PP_ADOL_ITXT",
                "PP_ADOL_WORK_PAID",
                "PP_ADOL_WORK_HOME",
            ],
            "default_graph": "bar",
            "default": "PP_ADOL_TVGM",
        },
    },
}


main_title = "Gender"


def get_layout(**kwargs):
    kwargs["indicators"] = indicators_dict
    kwargs["main_title"] = main_title
    kwargs["only_gender"] = True
    return get_base_layout(**kwargs)
